/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder096.geometry} material={materials['Black.012']} />
      <mesh geometry={nodes.Cylinder096_1.geometry} material={materials['Yellow.007']} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
