/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Sign.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sign.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sign_hospital_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.sign_hospital_1_1.geometry} material={materials.border} />
      <mesh geometry={nodes.sign_hospital_1_2.geometry} material={materials.roof} />
    </group>
  )
}

useGLTF.preload('/Sign.glb')
