/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Pine.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PineTree_mesh.geometry} material={materials.blinn3SG} />
    </group>
  )
}

useGLTF.preload('/Pine.glb')
